pydoit/doit

doit/filewatch.py
If a file is replaced it does change too.
For the OS X code path this change should be applied as well.  From a quick search fsevents.IN_MOVED_TO seems to exist but I have not verified it.
Btw. actually the safe way to "save" a file is to create a temp file and then move it over the original. So no other concurrently running process could read only half of it or in case of power failure the file would not corrupt.
=> listen for MOVED_TO events in doit auto

doc/tutorial/calc_dep.py, doc/tutorial/clean_mix.py, doc/tutorial/cproject.py, doc/tutorial/custom_cmd.py, doc/tutorial/getargs.py, doc/tutorial/getargs_dict.py, doc/tutorial/getargs_group.py, doc/tutorial/meta.py, doc/tutorial/my_dodo.py, doc/tutorial/my_tasks.py, doc/tutorial/parameters.py, doc/tutorial/parameters_inverse.py, doc/tutorial/pos.py, doc/tutorial/sample.py, doc/tutorial/subtasks.py, doc/tutorial/tsetup.py
Make tutorial-code py3 compatible.
- Fix print-statement.
- Drop {}.iterkeys().
- STILL left one `iteritems()` (doc/tutorial/cproject.py)
=> Py3 tutorial

doit/cmd_run.py, doit/control.py, doit/loader.py, doit/reporter.py, doit/task.py, tests/test_control.py
Allows to specify regexes for delayed task loaders, which allows to specify targets of delayed tasks with `doit run`.
If there is more than one regex matching a target, creates a task which has all potential tasks as a dependency and adds it to the list of selected tasks. This allows to specify any target created by a DelayedTask as long as it provides a regex which matches the target name.
There's an option to doit run called --auto-delayed-regex which takes '.*' as a regex for every delayed loaded task for which no regex is specified explicitely.
fixes #20
=> Delayed target regex

.travis.yml, appveyor.yml, doc/install.rst, tests/test_action.py, tests/test_cmd_auto.py, tests/test_cmd_info.py
This adds the AppVeyor config file (#56), and a few bonus fixes.
**Caveats:**
* The tests do not pass yet. I disabled `cmd_auto` testing on Windows (it hangs forever and is not supported anyway); there are also pickling errors.
* Python 3.2 is not supported on AppVeyor. Since you don’t have it in your trove classifiers, and most of the Python world dropped support for Python 3.2, I disabled it in Travis too.
**Setup:**
1. merge this
2. sign into AppVeyor with GitHub
3. create new project for `doit`
4. press “New build”
5. Go to settings, configure *Branches to build* manually (I tried doing it via the `appveyor.yml` file but it did not pick it up for me when I tested it)
6. You might also need to configure e-mail notifications in your profile.
(I also updated your install doc to drop …
=> Fix #56 -- add AppVeyor Windows CI

.travis.yml, .travis/install.sh, .travis/run.sh, AUTHORS
I added the ability to test Mac OS X on Travis CI. The solution is kind of heavy handed and involves changing a lot of .travis.yml and adding some helper scripts, but it works and it seems to be the only way to test Python projects on OS X. I used another repository for inspiration on how to format .travis.yml and write the scripts to allow for testing on OS X.
Here is a Travis CI build on my fork testing both Linux and OS X: https://travis-ci.org/philipbl/doit/builds/78691539
Currently, the OS X tests get stuck (as described in #101) and eventually time out. One of the tests (pypy3 on OS X) fails for other reasons, so I made that test optional.
=> Add tests for Mac OS X

tests/test_cmd_strace.py
AppVeyor now provides `strace` from `cygwin`. This fact was discovered in https://github.com/pydoit/doit/pull/114#issuecomment-158134093. This PR provides a quick fix for that problem.
Actually I didn't use `doit strace` command, maybe later someone who finds it useful will fix it on Windows :-)
=> Skip strace tests on windows and cygwin.

doc/cmd_other.rst
The doit list command shows tasks in alphabetical order, but the
documentation gives the impression that tasks are shown in some other
order. This can cause confusion for users expecting tasks to appear in
order of execution.
=> Clarify order of tasks shown by doit list command

AUTHORS, doit/dependency.py, tests/test_dependency.py
Only imports the SQLite module as required, as documented in [doit issue 153](https://github.com/pydoit/doit/issues/153).
This is useful in cases where python has been compiled without sqlite support but users want to use a different backend (e.g. json)
Includes a small unit test for this requirement.
=> Conditional SQLite import

.travis.yml, appveyor.yml, setup.py
This fixes #161. pip understands `extras_require` and uses them properly.
=> Fix #161 -- use extras_require to specify per-platform/per-Python dependencies

tests/test___main__.py, tests/test_action.py, tests/test_dependency.py, tests/test_task.py, tests/test_tools.py
Hello.
I met this issue when trying to run tests of doit module on a Python3-only system. Problem is that on a lot of systems `python` still means Python 2 and when you have only Python 3 installed, there is no `python` command at all.
I think that the best will be to execute commands inside test suite under the same Python as test suite itself.
This fix will also enable to run the test suite with various Python versions.
What do you think?
=> Use `executable` from `sys` module instead of hardcoded `python`

doc/dependencies.rst, doc/tasks.rst, doc/tutorial/report_deps.py
modified:   doc/dependencies.rst
modified:   doc/tasks.rst
new file:   doc/tutorial/report_deps.py
=> Doc: clarification on keyword argument use on {cmd,python}-action

tests/test_dependency.py
While preparing my development environment for the clean/forget command, I stumbled upon a failing test on Windows, Python 3.6.3, resulting from the fact that my GIT was checking out with crlf, leading to a different MD5 hash value.
I fixed the test by allowing both, the lf and crlf based hashes to be accepted. I verified the added hash in http://onlinemd5.com/.
It's weird that appveyor does not catch this, it seems to clone with lf only... Is that possible?
=> fixed MD5 test to also work if test file has been cloned with crlf endings

AUTHORS, CHANGES, doc/cmd_other.rst, doit/cmd_clean.py, tests/test_cmd_clean.py
Clean can now also forget about previous task execution be either adding the `--hard` option or by specifying `clean_hard=True` during doit configuration, see updated docs and unit tests.
This implements the feature request in #218.
=> added option to forget during clean

doit/cmd_info.py, doit/loader.py, tests/test_cmd_info.py
A few changes to make `doit info` nicer (imho): 
- Show the task docstring if it exists
- Better rendering for lists (`task_dep` etc.)
- And maybe controversial, show the status by default. I think that when using this command the status is one of the most useful information. 
Before:
```
❯ doit info ut
name:'ut'
task_dep:[   'ut:tests/test_loader.py',
'ut:tests/test_cmd_resetdep.py',
'ut:tests/test_doit_cmd.py',
'ut:tests/test_cmd_info.py',
'ut:tests/test_action.py',
'ut:tests/test_cmd_base.py',
'ut:tests/test_task.py',
'ut:tests/test_cmd_ignore.py',
'ut:tests/test_api.py',
'ut:tests/test_cmd_auto.py',
'ut:tests/test___init__.py',
'ut:tests/test_cmd_run.py',
'ut:tests/test_cmd_list.py',
'ut:tests/test_exceptions.py',
'ut:tests/test_control.py',
'ut:tests/test_cmd_help.py', …
```
=> Enhance readability of the info cmd, and print status by default.

doit/doit_cmd.py, tests/test_doit_cmd.py
This fixes #164.
This is a Windows-specific issue. For an explanation, see https://github.com/pydoit/doit/issues/164#issuecomment-369608965.
=> Guard against using get_var() on uninitialized _CMDLINE_VARS 

AUTHORS, CHANGES, doc/cmd_other.rst, doit/cmd_list.py, tests/test_cmd_list.py
The `--sort` option controls the order in which the tasks are listed.
Currently, two options are supported:
`name`: sort the tasks by name (the default)
`definition`: lists the tasks in the order in which they are defined
closes #207
=> Add option --sort to 'list' command

doc/stories.rst
I've started using `doit` at Atomwise, and it's working very well for various
data processing pipelines.
=> Adding Atomwise success story to `doit` repo

doc/tutorial_1.rst
Lots are trivial things, but even though English is not my native language, I humbly beleive it's a bit better now.
=> Minor modifications to the tutorial, mainly english aesthetics

README.rst
dev/bin/activate isn't an executable script, you need to source the file
into your local environment. Following the instructions as they are now
results in a "not executable by this user" error.
=> Fix development setup instructions

.gitignore, doc/tutorial/tuto_1_1.py, doc/tutorial_1.rst, doc_requirements.txt
Hey there,
Today I went through your tutorial and noticed a few things:
First I had to install the system package `graphviz-dev` for `pygraphviz` to be installed correctly. Not your fault, but I thought mentioning it will spare other people some time.
Then `import-dep` didn't run because there was a bug in pathlib usage. I've fixed that and opened a pull request there already.
Then I saw the same bug in the tutorial.
At first I thought I'd just open an issue, but then I thought it's so easy to fix that I might just as well *doit* myself. Less complaining, more doing :smile:
Anyway, here you go!
I've also fixed a few other things that I noticed along the way but not all of them.
The sample `report_deps.py` doesn't work and spellchecking also fails on a few files. I think `hunspell` should …
=> Fix pathlib bug in tutorial

AUTHORS, CHANGES, doit/task.py, tests/test_task.py
Had to switch to using `isinstance` in `Task.check_attr` to be able to use `collections.abc.Callable`. I think this change makes sense in general and not only to solve #286.
The minimum dodo file provided in #286's description now works (with minor modifications: had to swap `task` and `extra` parameters to `show_cmd`):
```python
#!/usr/bin/env python
import functools
def show_cmd(task, extra):
return '{}: executing... {}'.format(extra, task.name)
def task_lambda_ok():
return {
'actions':['echo lambda'],
'title': lambda task: show_cmd(task, 'LAMBDA')
}
def task_partial_ko():
title = functools.partial(show_cmd, extra='PARTIAL')
return {
'actions':['echo partial'],
'title': title,
}
```
=> Solve issue #286 - task.title accept partials

tests/test_cmd_completion.py
Unit tests raise these warnings:
```
============================== warnings summary ===============================
tests\test_cmd_completion.py:90
C:\projects\doit\tests\test_cmd_completion.py:90: DeprecationWarning: invalid escape sequence \]
assert ('"(-s|--lll)"{-s,--lll}"[my desc [b\]a]" \\' ==
tests\test_cmd_completion.py:97
C:\projects\doit\tests\test_cmd_completion.py:97: DeprecationWarning: invalid escape sequence \]
assert ('''"(-s|--lll)"{-s,--lll}"[my \\"des'c [b\]a]" \\''' ==
-- Docs: https://docs.pytest.org/en/latest/warnings.html
```
This PR fixes the two invalid escape sequences by replacing `\]` with `\\]`.
=> fix test warnings

doc/stories.rst
Here is the success story about how we replaced the existing `make`-based build system by `doit` on [MetalK8s](https://github.com/scality/metalk8s/).
Thanks for the great tool!
=> doc: add MetalK8s success story

tests/test_runner.py
Python 3.8 was able to pickle the previously unpicklable. Instead of relying on limits, let's raise an explicit error.
Fixes: #341
=> Py3.8: Replace recursive knot with explicitly unpicklable object

setup.py
Changes to how setuptools 50 works means that installing doit crashes with a cryptic KeyError (most likely caused by setuptools and pip’s monkeypatching of distutils). This check is not really necessary (most people have a newer pip these days).
---
Error:
```pytb
$ ./setup.py
/tmp/venv/lib64/python3.8/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
File "./setup.py", line 44, in <module>
setup(name = 'doit',
File "/tmp/venv/lib64/python3.8/site-packages/setuptools/__init__.py", line 152, in setup
_install_setup_requires(attrs)
File "/tmp/venv/lib64/python3.8/site-packages/setuptools/__init__.py", line 145, in _install_setup_requires …
```
=> Remove pip import and version check from setup.py to make doit install with setuptools 50.0

doc/tutorial_1.rst
This now matches the names of parameters in `tuto_1_2.py`
=> [doc] A few fixes in tutorial_1.rst

doit/reporter.py
Standard datetime to string conversion leaves open the possibility that in case of µs = 0, no decimals are displayed, which could break conversion back to datetime based on standard format.
=> Use uniform date format for TaskResult to_dict()

.github/workflows/ci.yml, .github/workflows/website.yml, dev_requirements.txt, doc/stories.rst, tests/test_action.py, tests/test_dependency.py
=> Add github actions

.github/workflows/ci.yml, README.rst, doc/dictionary.txt
A follow-up to https://github.com/pydoit/doit/pull/379#pullrequestreview-611689406, this uploads coverage to `codecov`, which is slightly simpler to set up, and doesn't require a secret token.
Also fixes a few spelling issues, just so we can see all the :heavy_check_mark: .
=> add codecov, tweak some spelling

doc/index.html
Having a release from 2019 makes it seem less active than the project is.
Python version range is updated to what was supported according to the build jobs at the time of the release.
=> Update version on home page

doit/cmd_info.py, doit/task.py, tests/test_cmd_info.py, tests/test_loader.py
The field is not interpreted by doit, but it can be used by plugins
A proposal according to the [conversation on the mailing list](https://groups.google.com/g/python-doit/c/nGzyDvD9QHc/m/qYjGc_clAAAJ). 
I am not sure about the name of the field. "meta" is a bit abstract, but it is short. Any other suggestions?
Maybe "hints"? Or "plugins"...?
Also I don't know where to put this in the docs...
=> Add field 'meta' to tasks that can be used by plugins

doit/cmd_completion.py
Currently tab completion does not work in gitbash, because windows does not use "/" as directory separator. The generated bash functions therefore do not have valid names. e.g.
complete -o filenames -F _C:\Users\user\AppData\Roaming\Python\Python310\Scripts\doit C:\Users\user\AppData\Roaming\Python\Python310\Scripts\doit
=> add tab completion support for gitbash

doc/samples/title.py
As far as I can tell, `doc/samples/title.py` is only used on the [tasks doc page](https://github.com/pydoit/doit/blob/master/doc/tasks.rst).
The **expected** output of `title.py`, as specified on the tasks page, is:
```
$ doit
.  executing... Cmd: echo abc efg
```
However, the **actual** output (before my proposed change) is:
```
doit                        
.  executing... custom_display
```
=> Correct title.py
